
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SECRET_KEY: ${SECRET_KEY}
        DEBUG: ${DEBUG}
        DATABASE_URL: ${DATABASE_URL}
        API_HOST: ${API_HOST}
        FRONTEND_URL1: ${FRONTEND_URL1}
        FRONTEND_URL2: ${FRONTEND_URL2}
    image: YOUR_IMAGE_NAME
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - API_HOST=${API_HOST}
      - FRONTEND_URL1=${FRONTEND_URL1}
      - FRONTEND_URL2=${FRONTEND_URL2}
    command: >
      sh -c "python3 manage.py migrate &&
             uvicorn ecommerce.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - new_volume:/app
    ports:
      - "8000:8000"

volumes:
  new_volume: