
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SECRET_KEY: ${SECRET_KEY}
        DEBUG: ${DEBUG}
        DATABASE_URL: ${DATABASE_URL}
        API_HOST: ${API_HOST}
        FRONTEND_URL1: ${FRONTEND_URL1}
        FRONTEND_URL2: ${FRONTEND_URL2}
    image: razevesigdel/ecommerce:latest
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - API_HOST=${API_HOST}
      - FRONTEND_URL1=${FRONTEND_URL1}
      - FRONTEND_URL2=${FRONTEND_URL2}
    volumes:
      - new_volume:/app/data
    ports:
      - "8000:8000"

volumes:
  new_volume: