# Generated by Django 5.0.4 on 2024-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='add_to_cart',
            field=models.BooleanField(default=True),
        ),
    ]
