name: ci

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update docker-compose.yml
        working-directory: './Backend'
        run: |
          sed -i "s/YOUR_IMAGE_NAME/${{ vars.DOCKER_USERNAME }}\/ecommerce:latest/g" docker-compose.yml
          sed -i "s/YOUR_SECRET_KEY/${{ secrets.SECRET_KEY }}/g" docker-compose.yml
          sed -i "s/YOUR_DATABASE_URL/${{ secrets.DATABASE_URL }}/g" docker-compose.yml
          sed -i "s/YOUR_API_HOST/${{ secrets.API_HOST }}/g" docker-compose.yml
          sed -i "s/YOUR_FRONTEND_URL1/${{ secrets.FRONTEND_URL1 }}/g" docker-compose.yml
          sed -i "s/YOUR_FRONTEND_URL2/${{ secrets.FRONTEND_URL2 }}/g" docker-compose.yml

      - name: Build and push Docker images
        working-directory: './Backend'
        run: |
          docker-compose build
          docker-compose push
        env:
          DOCKER_BUILDKIT: 1
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ vars.DEBUG }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_HOST: ${{ secrets.API_HOST }}
          FRONTEND_URL1: ${{ secrets.FRONTEND_URL1 }}
          FRONTEND_URL2: ${{ secrets.FRONTEND_URL2 }}
